model_identifier: "SimpleTransformer" 
num_heads: 8
layers: 10
batch_size: 64
context_length: 64
embedding_size: 256
dropout: 0.1
tokenizer_filename: "token_to_id.pkl"
tokenized_dataset: "tokenized_data.pkl"
tokenizer:
  type: "SimpleTokenizer"
dataloader:
  type: "SimpleTextDataset"
embedding_0:
  type: "SimplePositionalEmbedding"
embedding_1:
  type: "SimpleSemanticEmbedding"
architecture:
  type: "SimpleDecoder"