num_heads: 10
layers: 10
context_length: 512
tokenizer_filename: "token_to_id.pkl"
tokenized_dataset: "tokenized_data.pkl"
tokenizer:
  type: "SimpleTokenizer"
dataloader:
  type: "SimpleTextDataset"
embedding_0:
  type: "SimplePositionalEmbedding"
embedding_1:
  type: "SimpleSemanticEmbedding"
architecture:
  type: "SimpleDecoder"