name: Python Script Validation Workflow

on:
  push:
    branches:
      - main

jobs:
  run-and-validate:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          & "C:/Users/fawaz/AppData/Local/Programs/Python/Python310/python.exe" -m pip install --upgrade pip
          # If you have any dependencies, install them here

      - name: Run script
        run: |
          & "C:/Users/fawaz/AppData/Local/Programs/Python/Python310/python.exe" script.py

      - name: Validate results
        run: |
          & "C:/Users/fawaz/AppData/Local/Programs/Python/Python310/python.exe" validate.py
