name: Run and Validate Python Script in Docker

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  run-and-validate:
    runs-on: self-hosted  # Specify that this job should run on your self-hosted runner

    container:
      image: docker://my-python-app  # Use the Docker image you built
      env:
        SOME_ENV_VAR: "some-value"  # Optionally, set some environment variables

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This action checks out your repository so the runner can access your code

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # If you have any dependencies, install them here

      - name: Run script
        run: python script.py  # Run your script

      - name: Validate results
        run: python validate.py  # Run your validation script
