name: Run and Validate Python Script

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  run-and-validate:
    runs-on: self-hosted  # Specify that this job should run on your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This action checks out your repository so the runner can access your code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Use Python 3.10 for this job

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have any dependencies, install them here

      - name: Run script
        run: python script.py  # Run your script

      - name: Validate results
        run: python validate.py  # Run your validation script
        # This script should exit with a non-zero status code if validation fails

