name: Python Script Validation Workflow

on:
  push:
    branches:
      - main

jobs:
  run-and-validate:
    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies with Pipenv
      run: |
        pipenv install --dev

    - name: Run script.py using Pipenv
      run: |
        pipenv run python script.py

    - name: Run validate.py using Pipenv
      run: |
        pipenv run python validate.py