name: Run and Validate Python Script in Docker

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  run-and-validate:
    runs-on: self-hosted  # Specify that this job should run on your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This action checks out your repository so the runner can access your code

      - name: Run Docker in WSL
        run: |
          wsl -e bash -c "
            docker build -t mimi .
            docker run mimi /bin/bash -c 'python script.py && python validate.py'
          "
